#!/bin/bash


if [[ -e $HOME/.lsqrc ]]; then
    . $HOME/.lsqrc
fi

query=$1
# Shift $@ so we can hand the rest of it off to our pre-query script
shift

# Export qfile because our pre-query script will need it
export qfile="$LSQ_BASEDIR/queries/$query.lql"
pre_qfile="$LSQ_BASEDIR/queries/$query.pre"
post_qfile="$LSQ_BASEDIR/queries/$query.post"


#####################
# Pre-flight checks #
#####################

failed=0
for var in query LSQ_BASEDIR PORT TIMEOUT MONITORS; do
    if [[ -z "$(eval echo \$$var)" ]]; then
        echo "ERROR: no $var provided!"
        failed=1
    fi
done

if [[ $LSQ_BASEDIR =~ ^.*[\ ].*$ ]]; then
    echo "ERROR: Do not use an LSQ_BASEDIR with spaces in it!"
    failed=1
fi

if [[ ! -f $qfile ]] ; then
    echo "Query file for ($query) not found!"
    failed=1
fi

if [[ $failed -eq 1 ]]; then
    exit 1
fi


##############
# Main event #
##############

if [[ -x $pre_qfile ]]; then
    query_text=$($pre_qfile $@)
    if [[ $? -ne 0 ]]; then
        echo "Pre-query script exited with error:"
        echo
        echo $query_text
        exit 1
    fi
else
    query_text=$(cat $qfile)
fi

[[ -d $LSQ_BASEDIR/tmp ]] || mkdir "$LSQ_BASEDIR/tmp"
for monitor in ${MONITORS[@]}; do
    outfile="$LSQ_BASEDIR/tmp/$monitor.$$"
    nc -w$TIMEOUT $monitor $PORT < <(echo "$query_text") > $outfile \
        || echo "ERROR: Failed to query monitor: $monitor" 1>&2 &
done
wait

cmd="cat $LSQ_BASEDIR/tmp/*.$$"


if [[ -x $post_qfile ]]; then
    cmd=$cmd"| $post_qfile"
elif [[ -x $LSQ_BASEDIR/queries/default.post ]]; then
    cmd="$cmd | \"$LSQ_BASEDIR/queries/default.post\""
fi

eval "$cmd"
rm $LSQ_BASEDIR/tmp/*.$$
