#!/bin/bash


if [[ -e $HOME/.lsqrc ]]; then
    . $HOME/.lsqrc
fi

query=$1
# Shift $@ so we can hand the rest of it off to our pre-query script
shift

# Export qfile because our pre-query script will need it
export qfile="$LSQ_BASEDIR/queries/$query.lql"
pre_qfile="$LSQ_BASEDIR/queries/$query.pre"
post_qfile="$LSQ_BASEDIR/queries/$query.post"


#####################
# Pre-flight checks #
#####################

failed=0
error=""

for var in query LSQ_BASEDIR PORT TIMEOUT MONITORS; do
    if [[ -z "$(eval echo \$$var)" ]]; then
        error="${error}\n- No $var provided!"
        failed=1
    fi
done

if [[ $LSQ_BASEDIR =~ ^.*[\ ].*$ ]]; then
    error="${error}\n- Do not use an LSQ_BASEDIR with spaces in it!"
    failed=1
fi

if [[ ! -f $qfile ]] ; then
    error="${error}\n- Query file for ($query) not found!"
    failed=1
fi

LSQ_TMPDIR=$(mktemp -d)
if [[ ! -d $LSQ_TMPDIR ]]; then
    error="${error}\n- Failed to create tmp directory"
    failed=1
fi

if [[ $failed -eq 1 ]]; then
    echo "Uh-oh, we ran into some problems:"
    echo -e $error
    exit 1
fi

#############
#  Helpers  #
#############

function cleanup {
    rm -rf "$LSQ_TMPDIR"
}

##############
# Main event #
##############

trap cleanup EXIT SIGTERM SIGINT

# Try a pre-query script and bail out if it fails with a non-zero exit status
if [[ -x $pre_qfile ]]; then
    query_text=$($pre_qfile $@)
    exit_status=$?
    if [[ $exit_status -ne 0 ]]; then
        echo -ne "Pre-query script exited with error:\n\n"
        echo "$query_text"
        exit $exit_status
    fi
else
    query_text=$(cat $qfile)
fi

for monitor in ${MONITORS[@]}; do
    outfile="$LSQ_TMPDIR/$monitor.$$"
    printf "%s\n\n" "$query_text" \
        | nc -w$TIMEOUT $monitor $PORT > $outfile \
        || echo "ERROR: Failed to query monitor: $monitor" 1>&2 &
done
wait

cmd="cat $LSQ_TMPDIR/*.$$"


if [[ -x $post_qfile ]]; then
    cmd=$cmd"| $post_qfile"
elif [[ -x $LSQ_BASEDIR/queries/default.post ]]; then
    cmd="$cmd | \"$LSQ_BASEDIR/queries/default.post\""
fi

eval "$cmd"
